/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface YtVid {
        "allow"?: string;
        "allowfullscreen": boolean;
        "alt"?: string;
        "customPlayIcon"?: string;
        "height"?: string;
        "src": string;
        "width"?: string;
    }
}
declare global {
    interface HTMLYtVidElement extends Components.YtVid, HTMLStencilElement {
    }
    var HTMLYtVidElement: {
        prototype: HTMLYtVidElement;
        new (): HTMLYtVidElement;
    };
    interface HTMLElementTagNameMap {
        "yt-vid": HTMLYtVidElement;
    }
}
declare namespace LocalJSX {
    interface YtVid {
        "allow"?: string;
        "allowfullscreen"?: boolean;
        "alt"?: string;
        "customPlayIcon"?: string;
        "height"?: string;
        "src"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "yt-vid": YtVid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "yt-vid": LocalJSX.YtVid & JSXBase.HTMLAttributes<HTMLYtVidElement>;
        }
    }
}
